
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-10T08:34:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad54e894185c746ab402eebe2b0e774544ed5b32",
 "version": "1.10.0.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
