name: Build Release
on:
  push:
    tags:
      - "v*"
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macOS-10.15, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.0.0a2
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD_WINDOWS: pip3 install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html --ignore-installed
          CIBW_BEFORE_BUILD_MACOS: pip3 install torch==1.9.0 -f https://download.pytorch.org/whl/torch_stable.html --ignore-installed
          CIBW_BEFORE_BUILD_LINUX: pip3 install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html --ignore-installed
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_BUILD: cp37-* cp38-* cp39-*
          CIBW_SKIP: "*-manylinux_i686 *-win32"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
      - uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl
      - name: Upload files to release
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ needs.create_release.outputs.upload_url }}
          pattern: "./wheelhouse/*.whl"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build_sdist:
    name: Build source distributions
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.8"
      - uses: Jimver/cuda-toolkit@v0.2.2
        name: Install CUDA
        id: cuda-toolkit
        with:
          cuda: "11.2.2"
      - name: Build memtorch and memtorch-cpu sdist
        run: |
          python -m pip install -r requirements.txt
          python setup.py sdist
          sed -i 's/CUDA = False/CUDA = True/g' setup.py
          python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: dist/*.tar.gz
      - name: Upload files to release
        uses: csexton/release-asset-action@v2
        with:
          pattern: "dist/*.tar.gz"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ needs.create_release.outputs.upload_url }}
