name: Codecov
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Coverage Report
      run: |
        pip install pytest
        pip install codecov
        pip install pytest-cov
        git submodule update --init --recursive
        python -m pip install -r requirements_linux_osx.txt
        python setup.py install
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage1.xml,./coverage2.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
