name: Lint
on: 
  push:
  pull_request:
jobs:
  linter_name:
    name: Clang Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: 'memtorch/cpp/ memtorch/cu/'
        exclude: './third_party ./external'
        extensions: 'h,cpp,cu'
        clangFormatVersion: 12   
