name: Lint
on: 
  push:
  pull_request:
jobs:
  linter_name:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-black@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
