name: Lint
on: [push, pull_request]
jobs:
  linter:
    name: Lint Formatters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Files Using the Black Formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Check files Using the Clang Formatter
        uses: DoozyX/clang-format-lint-action@v0.12
        id: action_clang
        with:
          source: "memtorch/cpp memtorch/cu"
          extensions: "h,cpp,c,cu"
          clangFormatVersion: 12
          inplace: True
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: action_pull_request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Enforced Python/C++/CUDA Code Formatting with Black and Clang"
          commit-message: ":art: Enforced Python/C++/CUDA Code Formatting with Black and Clang"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This automatically generated pull request uses the [psf/black](https://github.com/psf/black) and [clang](https://clang.llvm.org/docs/ClangFormat.html) formatters to fix these issues.
          base: ${{ github.head_ref }}
          branch: actions/lint
      - name: "Trigger Next Workflow"
        if: ${{ steps.cpr.outputs.pull-request-number == "" }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
