name: Build
on: [push, pull_request] # Temp- to change to on tag beginning with v.
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15] # windows-2019
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.0.0a2
          if [[ ${{ matrix.os }} == "ubuntu-20.04" ]]; then
            sudo apt-get install -y ninja-build
            sudo apt-get install -y libc6
          fi
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: python3 -m pip install -r requirements_linux_osx.txt

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
