name: Build
on: [push, pull_request] # Temp- to change to on tag beginning with v.
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macOS-10.15] # ,ubuntu-20.04,
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.0.0a2
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD_WINDOWS: |
            python -m pip install -r requirements_windows_cpu.txt
            pip install torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html --ignore-installed
          CIBW_BEFORE_BUILD_MACOS: |
            python -m pip install -r requirements_linux_osx.txt
            pip install torch==1.8.1 -f https://download.pytorch.org/whl/torch_stable.html --ignore-installed
          # CIBW_BEFORE_BUILD: python -m pip install -r requirements_linux_osx.txt
          #   if [[ ${{ matrix.os }} == "ubuntu-20.04" || ${{ matrix.os }} == "windows-2019" ]]; then
          #     pip3 install torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          #   fi
          #   python -m pip install -r requirements_linux_osx.txt
          #   if [[ ${{ matrix.os }} != "windows-2019" ]]; then
          #     lib=$(dirname $(find / -name libtorch_cpu.so | grep -m1 .))
          #     echo $lib
          #   fi
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_BUILD: cp37-* cp38-* cp39-*
          CIBW_SKIP: "*-manylinux_i686"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
